FROM jboss/keycloak:1.9.5.Final

ADD changeDatabase.jq /opt/jboss/keycloak/

RUN INPUT=`cat /opt/jboss/keycloak/standalone/configuration/keycloak-server.json` && echo $INPUT | jq -f /opt/jboss/keycloak/changeDatabase.jq > /opt/jboss/keycloak/standalone/configuration/keycloak-server.json &&\
sed -i '/<socket-binding-group/a <socket-binding name="proxy-https" port="443"/>' keycloak/standalone/configuration/standalone-ha.xml &&\
sed -i 's/redirect-socket="https"/redirect-socket="proxy-https" proxy-address-forwarding="true"/g' keycloak/standalone/configuration/standalone-ha.xml

CMD ["-b", "0.0.0.0", "--server-config", "standalone-ha.xml"]
